export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_ALL_COMPLAINTS = 'FETCH_ALL_COMPLAINTS';
export const FETCH_COMPLAINTS_BY_STATUS = 'FETCH_COMPLAINTS_BY_STATUS';
export const FETCH_COMPLAINTS_COUNT = 'FETCH_COMPLAINTS_COUNT';

export const SELECT_COMPLAINT = 'SELECT_COMPLAINT';
export const UPDATE_COMPLAINT_LIST = 'UPDATE_COMPLAINT_LIST';

export const RECEIVED = 'RECEIVED';
export const CLOSED = 'CLOSED';
export const INPROGRESS = 'INPROGRESS';